<?php

namespace AppBundle\Repository;

use AppBundle\Entity\User;

/**
 * UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRepository extends \Doctrine\ORM\EntityRepository
{
    public function getUserPassword(string $username){
        $user = $this->findOneBy(array('username'=>$username));
       return( $user->getPassword());
        //        $query=$this->createQueryBuilder('u')
//            ->from('User')
//            ->where('u.username=:username')
//            ->setParameters(['username'=>$username])
//            ->getQuery();
//        $query->getResult();
//        echo ((string)$query);
//        return;
    }
    public function getUserEmail(string $username)
    {
        $user = $this->findOneBy(array('username' => $username));
        return ($user->getEmail());
    }

}
